export type Module =
  | "beginSpringA"
  | "beginSpringB"
  | "beginSpringC"
  | "beginFallA"
  | "beginFallB"
  | "beginFallC"
  | "SAE"
  | "SBE"
  | "SCE"
  | "FAE"
  | "FBE"
  | "FCE"
  | "springABCEndDate"
  | "fallABCEndDate";
